### ISSUE TITLE
Add support for Dash

### ISSUE THREAD

**Issue by we11adam** [sydlawrence/alfred-dev-doctor#22]
Well, before applying Dev Doctor, I've been using Dash to look up APIs. Dev Doctor takes API browsing to a whole new level. 

It would be even much better if Dev Doctor opens the API page directly in Dash,  instead of opening a webpage. 

Hope this can be implemented. :)

BTW: Dash can be obtained at http://itunes.apple.com/us/app/dash/id458034879?ls=1&mt=12

**Comment by Kapeli** [comment]
I'm Dash's developer. The next update of Dash (version 1.8.2 - currently waiting for review) will include its own Alfred workflow which is similar to Dev Doctor and will look something like this: http://cl.ly/image/0h2r0d3b1c2h.

I don't think there's a point of getting Dev Doctor to open pages in Dash, since the pages Dev Doctor deals with are online afaik and there would be no benefit as opposed to opening in your regular web browser (e.g. you wouldn't get the filterable table of contents).

To @sydlawrence: sorry for hijacking this thread!

**Comment by we11adam** [comment]
Thanks for providing a native workflow,@kapeli :)

This issue is considered closed.
